{
 "title": "Netology 10.3 Grafana",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{job=\"node_exporter\", mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU LA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{instance=\"node_exporter:9100\"}"
    },
    {
     "expr": "node_load5{instance=\"node_exporter:9100\"}"
    },
    {
     "expr": "node_load15{instance=\"node_exporter:9100\"}"
    }
   ]
  },
  {
   "title": "RAM USED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"node_exporter\"} * 100) - node_memory_MemFree_bytes{job=\"node_exporter\"} / node_memory_MemTotal_bytes"
    }
   ]
  },
  {
   "title": "HDD Free %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs\"} * 100"
    }
   ]
  }
 ]
}